exclude: '.git|.tox'
default_stages: [commit]

repos:
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variables']
      language_version: python3.10
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3.10
-   repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
      args: [--line-length, '80']
      language_version: python3.10
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: check-builtin-literals
