version: 2.1
commands:
  prepare_env:
    steps:
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools wheel twine build pytest pytest-cov ipython icecream

  generate_test_pypirc:
    steps:
      - run:
          command: |
            echo -e "[distutils]\nindex-servers =\n    testpypi\n\n[testpypi]\nusername: __token__\npassword: $TEST_PYPI_TOKEN" > ~/.pypirc

  generate_pypirc:
    steps:
      - run:
          command: |
            echo -e "[distutils]\nindex-servers =\n    pypi\n\n[pypi]\nusername = __token__\npassword = $PYPI_TOKEN" > ~/.pypirc

jobs:
  test:
    parameters:
      docker_version:
        type: string
    docker:
      - image: << parameters.docker_version >>
    steps:
      - checkout
      - prepare_env
      - run:
          command: |
            . venv/bin/activate
            pytest simpleregex/tests/

  test_pypi_publish:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - prepare_env
      - generate_test_pypirc
      - run:
          command: |
            . venv/bin/activate
            python3 -m build .
            python3 -m twine upload -r testpypi dist/* --verbose

  pypi_publish:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - prepare_env
      - generate_pypirc
      - run:
          command: |
            . venv/bin/activate
            python3 -m build .
            python3 -m twine upload -r pypi dist/* --verbose

workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              docker: ["cimg/python:3.7", "cimg/python:3.8", "cimg/python:3.9", "cimg/python:3.10", "cimg/python:3.11"]
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only:
                - main
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - test_pypi_publish:
          requires:
            - hold
          filters:
            branches:
              only:
                - main
      - pypi_publish:
          requires:
            - hold
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
