version: 2.1
jobs:
  test-py38: &test-template
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip install poetry
            poetry install --no-ansi
      - run:
          command: |
            poetry run pytest simpleregex/tests/
  test-py39:
    <<: *test-template
    docker:
      - image: cimg/python:3.9

  test-py310:
    <<: *test-template
    docker:
      - image: cimg/python:3.10
  test-py311:
    <<: *test-template
    docker:
      - image: cimg/python:3.11
  test_pypi_publish:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: |
            echo "Hello World!"
workflows:
  publish_test_pypi:
    jobs:
      - test-py38
      - test-py39
      - test-py310
      - test-py311
      - test_pypi_publish:
          requires:
            - test-py38
            - test-py39
            - test-py310
            - test-py311
          filters:
            branches:
              only:
                - feature/BN-4408
