version: 2.1
commands: # a reusable command with parameters
  prepare_env:
    steps:
      - run:
          command: | # poetry install --no-ansi due to cleo issue for petry >1.2.2 and circle python images < 3.11 https://github.com/python-poetry/poetry/issues/7184
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip install --user --upgrade setuptools wheel twine
            

jobs:
  test-py37: &test-template
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - prepare_env
      - run:
          command: |
            pytest simpleregex/tests/

  test-py38:
    <<: *test-template
    docker:
      - image: cimg/python:3.8

  test-py39:
    <<: *test-template
    docker:
      - image: cimg/python:3.9

  test-py310:
    <<: *test-template
    docker:
      - image: cimg/python:3.10

  test-py311:
    <<: *test-template
    docker:
      - image: cimg/python:3.11

  test_pypi_publish:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - prepare_env
      - run:
          command: |
              python3 -m build .
              python3 -m twine upload -r pypi/testpypi dist/*

  pypi_publish:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - prepare_env
      - run:
          command: |
              python3 -m build .
              python3 -m twine upload -r pypi/testpypi dist/*

workflows:
  main:
    jobs:
      - test-py37
      - test-py38
      - test-py39
      - test-py310
      - test-py311
      - hold:
          type: approval
          requires:
            - test-py37
            - test-py38
            - test-py39
            - test-py310
            - test-py311
          filters:
            branches:
              only:
                - main
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - test_pypi_publish:
          requires:
            - hold
          filters:
            branches:
              only:
                - main
      - pypi_publish:
          requires:
            - hold
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
