version: 2.1
commands: # a reusable command with parameters
  :
    steps:
      - run:
          command: | # poetry install --no-ansi due to cleo issue for petry >1.2.2 and circle python images < 3.11 https://github.com/python-poetry/poetry/issues/7184
            sudo curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
            poetry install --no-ansi
jobs:
  test-py38: &test-template
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - prepare_env
      - run:
          command: |
            poetry run pytest simpleregex/tests/
  test-py39:
    <<: *test-template
    docker:
      - image: cimg/python:3.9

  test-py310:
    <<: *test-template
    docker:
      - image: cimg/python:3.10
  test-py311:
    <<: *test-template
    docker:
      - image: cimg/python:3.11
  test_pypi_publish:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          command: |
            echo "Hello World!"
workflows:
  publish_test_pypi:
    jobs:
      - test-py38
      - test-py39
      - test-py310
      - test-py311
      - test_pypi_publish:
          requires:
            - test-py38
            - test-py39
            - test-py310
            - test-py311
          filters:
            branches:
              only:
                - feature/BN-4408
