version: 2.1
commands: # a reusable command with parameters
  prepare_env:
    steps:
      - run:
          command: | # poetry install --no-ansi due to cleo issue for petry >1.2.2 and circle python images < 3.11 https://github.com/python-poetry/poetry/issues/7184
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip install poetry < 1.4.0
            poetry install --no-ansi
  configure_build:
    parameters:
      repository:
        default: "test-pypi"
        type: string
      pypi_url:
        default: "https://test.pypi.org/legacy/"
        type: string
      pypi_token:
        default: "TEST_PYPI_TOKEN"
        type: string
    steps:
      - run:
          command: |
            poetry config repositories.<<parameters.repository>> <<parameters.pypi_url>>
            poetry config pypi-token.<<parameters.repository>> $<<parameters.pypi_token>>
  build_publish:
    steps:
      - run:
          command: |
            poetry build
            poetry publish -r test-pypi

jobs:
  test-py37: &test-template
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - prepare_env
      - run:
          command: |
            poetry run pytest simpleregex/tests/

  test-py38:
    <<: *test-template
    docker:
      - image: cimg/python:3.8

  test-py39:
    <<: *test-template
    docker:
      - image: cimg/python:3.9

  test-py310:
    <<: *test-template
    docker:
      - image: cimg/python:3.10

  test-py311:
    <<: *test-template
    docker:
      - image: cimg/python:3.11

  test_pypi_publish:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - prepare_env
      - configure_build
      - run:
          command: |
            poetry version "$(poetry version)+dev${CIRCLE_BUILD_NUM}"
      - build_publish

workflows:
  publish_test_pypi:
    jobs:
      - test-py37
      - test-py38
      - test-py39
      - test-py310
      - test-py311
      - test_pypi_publish:
          requires:
            - test-py37
            - test-py38
            - test-py39
            - test-py310
            - test-py311
          filters:
            branches:
              only:
                - feature/BN-4408
