version: 2.1
jobs:
  test-py3.8: &test-template
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip install poetry
            poetry install
      - run:
          command: |
            poetry run pytest simpleregex/tests/
  test-py3.9:
    <<: *test-template
    docker:
      - image: circleci/python:3.9

  test-py3.10:
    <<: *test-template
    docker:
      - image: circleci/python:3.10
  test-py3.11:
    <<: *test-template
    docker:
      - image: circleci/python:3.11
  test_pypi_publish:
    docker:
      - image: cimg/python:3.10.10
    steps:
      - checkout
      - run:
          command: |
            echo "Hello World!"
workflows:
  run_tests:
    jobs:
      - test-py3.8
      - test-py3.9
      - test-py3.10
      - test-py3.11
  publish_test_pypi:
    jobs:
      - test_pypi_publish:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - feature/BN-4408
